name:                interactive-plot
version:             0.1.0.0
github:              "mstksg/interactive-plot"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"
tested-with:         GHC >= 8.4 && < 8.8

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Interactive quick time series plotting
category:            Interactive

description: |
  Quick time series terminal plotting for data exploration/in ghci. See
  documentation for "Interactive.Plot" and README for more information.

dependencies:
- base >= 4.11 && < 5

ghc-options:
- -Wall
- -Wredundant-constraints
- -Werror=incomplete-patterns
- -Wcompat

library:
  source-dirs: src
  dependencies:
  - MonadRandom
  - containers >= 0.5.11
  - data-default-class
  - bytestring
  - microlens
  - microlens-th
  - mtl
  - transformers
  - utf8-string
  - vty

executables:
  interactive-plot-demo:
    main:                demo.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - interactive-plot
