name:                interactive-plot
version:             0.1.0.0
github:              "mstksg/interactive-plot"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Quick time series plotting meant to be used interactively in ghci
category:            Interactive

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/interactive-plot#readme>

dependencies:
- base >= 4.7 && < 5
- vty
- transformers
- containers
- MonadRandom
- mtl
- microlens
- microlens-platform
- microlens-th
- data-default

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  interactive-plot-demo:
    main:                demo.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - interactive-plot

# tests:
#   interactive-plot-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - interactive-plot
